name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev
        
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # zlib is pre-installed on macOS
        brew install gcc || true
        
    - name: Build
      run: make
      
    - name: Test build
      run: |
        ./srr2illumina --help || echo "Help command test completed"
        ls -la srr2illumina
        file srr2illumina
        
    - name: Clean
      run: make clean
